# Generated by Django 5.2.7 on 2025-12-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.IntegerField(max_length=100)),
                ('dept', models.CharField()),
                ('job', models.CharField()),
                ('salary', models.IntegerField()),
                ('gender', models.CharField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
