# Generated by Django 5.2.7 on 2026-01-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_categorymodelclass_productmodelclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodelclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
