# Generated by Django 5.2.7 on 2026-01-24 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productmodelclass_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModelClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmodelclass')),
            ],
        ),
    ]
